title: Carlos García
# author: Carlos García
# logo: 
description: >-
  Bookmark this to keep an eye on my project updates!<br>
  <span class="social">
    <a href="https://www.linkedin.com/in/ce-garcía/" aria-label="LinkedIn" target="_blank" rel="noopener">
      <img src="/assets/icons/linkedin.svg" alt="LinkedIn" width="22" height="22">
    </a>
    &nbsp;
    <a href="mailto:cegarciadd@gmail.com" aria-label="Email">
      <img src="/assets/icons/email.svg" alt="Email" width="22" height="22">
    </a>
  </span>
  
# show_downloads: false # adds a button that lets you download the repositoy 
theme: jekyll-theme-minimal

show_social: true

linkedin_url: https://www.linkedin.com/in/ce-garcía
email: cegarciadd@gmail.com
